[package]
name = "pixwiz"
version = "0.1.0"
authors = ["Andy C King <andycking@fastmail.com>"]
edition = "2018"

[dependencies.druid]
version = "0.7.0"
features = ["png"]
git = "https://github.com/linebender/druid"

[dependencies.png]
